In [1]:
print('heloo there')

heloo there


In [3]:
import numpy as np
asd='starting numpy'
print (asd)

starting numpy


In [4]:
a=np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [34]:
b=np.array([[1,2,3],[45,67,89]])
print (b)
print(b.itemsize)

[[ 1  2  3]
 [45 67 89]]
4


In [31]:
c=np.array([1,2,3,45,7],ndmin=2)
print (c)

[[ 1  2  3 45  7]]


In [16]:
d= np.array([45.0+2j,56+3j,68],dtype=complex)
print (d)

[45.+2.j 56.+3.j 68.+0.j]


In [48]:
ab=np.array([[1,2,3,4],[34,56,78,234],[34,67,35,90]])
print (ab)
print(ab.shape)
print(ab[1:])
print(ab[:2])
ab.shape=(6,2)
print (ab)

SyntaxError: invalid syntax (<ipython-input-48-a8d30ae0b01b>, line 6)

In [26]:
cd=ab.reshape(4,3)
print(cd)

[[  1   2   3]
 [  4  34  56]
 [ 78 234  34]
 [ 67  35  90]]


In [35]:
sa=np.arange(50)
print(sa)
sa.ndim
sd=sa.reshape(5,2,5)
print (sd)
print (sd.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]
4


In [39]:
df=np.array([1,2,34,45],dtype=np.int8)
print (df.itemsize)
df1=np.array([1,2,34,45],dtype=np.float32)
print (df1.itemsize)
print (df.flags)

1
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [42]:
z=np.arange(12)
print(z[3:])
print(z[4:9])
print(z[:8])

[ 3  4  5  6  7  8  9 10 11]
[4 5 6 7 8]
[0 1 2 3 4 5 6 7]
