In [36]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[12,23,34],[45,56,67],[78,89,90]])
e=np.array([4,5,6])
f=np.array([[7],[8],[9]])
print(a+f)
c=a+b
d=a*b
print (a+e)
print(a*e)
print (c)
print (d)
print (np.append(a,[10,11,12]))
print (a)
print (np.append(a,[[10,11,12]],axis=0))
print (a)
print (a.reshape(1,9))
print (np.reciprocal(a))
i =np.linalg.inv(a)
print (a*i)
print (np.linalg.inv(a))
print (np.linalg.det(a))

[[ 8  9 10]
 [12 13 14]
 [16 17 18]]
[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 4 10 18]
 [16 25 36]
 [28 40 54]]
[[13 25 37]
 [49 61 73]
 [85 97 99]]
[[ 12  46 102]
 [180 280 402]
 [546 712 810]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[ 3.15251974e+15 -1.26100790e+16  9.45755922e+15]
 [-2.52201579e+16  6.30503948e+16 -3.78302369e+16]
 [ 2.20676382e+16 -5.04403158e+16  2.83726777e+16]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
-9.51619735392994e-16


In [37]:
g=np.arange(0,60,5)
g=g.reshape(3,4)
print (g)
print (g.T)
for i in np.nditer(g):
    print (i)
print (g.transpose())
print (g.reshape(6,2))
print (np.cos((g*np.pi/180)))
print (np.sin(g*np.pi/180))
print (np.power(g,2))


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
[[1.         0.9961947  0.98480775 0.96592583]
 [0.93969262 0.90630779 0.8660254  0.81915204]
 [0.76604444 0.70710678 0.64278761 0.57357644]]
[[0.         0.08715574 0.17364818 0.25881905]
 [0.34202014 0.42261826 0.5        0.57357644]
 [0.64278761 0.70710678 0.76604444 0.81915204]]
[[   0   25  100  225]
 [ 400  625  900 1225]
 [1600 2025 2500 3025]]


In [30]:
h= np.array([1.2,2.3,3.4,4.5,5.6,-6.7,-7.3])
print (np.ceil(h))
print (np.floor(h))

[ 2.  3.  4.  5.  6. -6. -7.]
[ 1.  2.  3.  4.  5. -7. -8.]
